plugins:
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/RenoFi/rubocop/main/ruby.yml
  - https://raw.githubusercontent.com/RenoFi/rubocop/main/rspec.yml

AllCops:
  TargetRubyVersion: 3.3

Gemspec/RequiredRubyVersion:
  Include:
    - 3.3
    - 3.4

Naming/FileName:
  Exclude:
    - 'lib/*.rb'
