require:
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/RenoFi/rubocop/main/ruby.yml
  - https://raw.githubusercontent.com/RenoFi/rubocop/main/rspec.yml

AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Include:
    - 2.6
    - 2.7
    - 3.0

Naming/FileName:
  Exclude:
    - 'lib/*.rb'
