plugins:
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/RenoFi/rubocop/main/.rubocop-ruby.yml
  - https://raw.githubusercontent.com/RenoFi/rubocop/main/.rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 3.4

Gemspec/RequiredRubyVersion:
  Include:
    - 3.4
    - 4.0

Naming/FileName:
  Exclude:
    - 'lib/*.rb'
