version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "[dependabot]"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
    labels:
      - "automerge"
      - "dependencies"
