name: automerge
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge-labeled:
    if: >
      github.event.pull_request.user.login != 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'automerge') &&
      !contains(github.event.pull_request.labels.*.name, 'automerge blocked')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge-dependabot:
    if: >
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      !contains(github.event.pull_request.labels.*.name, 'automerge blocked')
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve minor and patch
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for minor and patch
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge-update-branch:
    if: github.event_name == 'check_suite'
    runs-on: ubuntu-latest
    steps:
      - name: Update branches behind base
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list --repo "$GITHUB_REPOSITORY" \
            --label automerge \
            --limit 100 \
            --json number,labels \
            --jq '.[] | select(.labels | map(.name) | contains(["automerge blocked"]) | not) | .number' \
            | while read pr_number; do
            gh pr update-branch "$pr_number" --repo "$GITHUB_REPOSITORY" 2>/dev/null || true
          done
